"""End-to-end demonstration of the Phase 1 deliverables.

Phase 1 asks for three things: a narrow natural-language interface covering
four or five question types, light QEMU integration for basic reachability, and
measured precision on the evaluation suite. This checks each of them against
real analysis, printing PASS or FAIL, and exits non-zero if any fails.

    python examples/demo_phase1.py

Nothing is mocked. The firmware image is generated by examples/src/ and
unpacked for real; the Ghidra and QEMU stages import recorded outputs, because
neither engine is a reasonable prerequisite for a demonstration - and the import
path is exactly the one a live run feeds into.

Nothing here executes a target binary. Reachability comes from a recorded
trace; see docs/adr/0007-emulation-is-opt-in.md for why that is the default.
"""

from __future__ import annotations

import os
import runpy
import shutil
import sys
import tempfile

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, REPO_ROOT)

from aether.adapters.binwalk import BinwalkAdapter  # noqa: E402
from aether.adapters.ghidra import GhidraAdapter  # noqa: E402
from aether.adapters.qemu import QemuAdapter  # noqa: E402
from aether.adapters.triage import TriageAdapter  # noqa: E402
from aether.errors import AdapterError  # noqa: E402
from aether.eval import load_suite, run_question_suite  # noqa: E402
from aether.mcp.server import MCPServer  # noqa: E402
from aether.nl import ask  # noqa: E402
from aether.nl.model import validate_answer  # noqa: E402
from aether.nl.questions import QUESTION_TYPES  # noqa: E402
from aether.project import Project  # noqa: E402

EXAMPLES = os.path.join(REPO_ROOT, "examples")
ELF = os.path.join(EXAMPLES, "firmware_agent.elf")
FIRMWARE = os.path.join(EXAMPLES, "demo_firmware.bin")
GHIDRA_EXPORT = os.path.join(REPO_ROOT, "tests", "fixtures", "ghidra", "firmware_agent")
QEMU_TRACE = os.path.join(
    REPO_ROOT, "tests", "fixtures", "qemu", "firmware_agent.exec.log"
)
NL_SUITE = os.path.join(REPO_ROOT, "eval", "suites", "nl_questions.json")

RESULTS: list[tuple[str, bool, str]] = []


def check(name: str, condition: bool, detail: str = "") -> bool:
    RESULTS.append((name, bool(condition), detail))
    print(f"  [{'PASS' if condition else 'FAIL'}] {name}" + (f"  -  {detail}" if detail else ""))
    return bool(condition)


def heading(text: str) -> None:
    print(f"\n{text}\n{'-' * len(text)}")


def _run_script(path: str, *args: str) -> None:
    saved = sys.argv
    sys.argv = [path, *args]
    try:
        runpy.run_path(path, run_name="__main__")
    except SystemExit as exc:
        if exc.code not in (0, None):
            raise
    finally:
        sys.argv = saved


def build_inputs() -> None:
    heading("0. inputs")
    if not os.path.isfile(ELF):
        _run_script(os.path.join(EXAMPLES, "src", "build_elf_sample.py"), ELF)
    if not os.path.isfile(FIRMWARE):
        _run_script(os.path.join(EXAMPLES, "src", "build_firmware_sample.py"), FIRMWARE)
    if not os.path.isfile(os.path.join(GHIDRA_EXPORT, "meta.json")):
        _run_script(os.path.join(REPO_ROOT, "tests", "fixtures", "make_ghidra_fixture.py"))
    if not os.path.isfile(QEMU_TRACE):
        _run_script(os.path.join(REPO_ROOT, "tests", "fixtures", "make_qemu_fixture.py"))
    check("firmware image present", os.path.isfile(FIRMWARE), os.path.basename(FIRMWARE))
    check("recorded Ghidra export present", os.path.isfile(os.path.join(GHIDRA_EXPORT, "meta.json")))
    check("recorded QEMU trace present", os.path.isfile(QEMU_TRACE), os.path.basename(QEMU_TRACE))


def main() -> int:
    print("Aether - Phase 1 demonstration")
    print("=" * 62)
    build_inputs()

    workspace = tempfile.mkdtemp(prefix="aether-p1-")
    project = Project.create(os.path.join(workspace, "project"), "phase1-demo")

    try:
        heading("1. analysis under test")
        BinwalkAdapter().analyze(project, FIRMWARE, logical_path="demo_firmware.bin")
        agent = project.resolve_object("bin/firmware_agent")
        check(
            "firmware unpacked and inventoried",
            agent is not None,
            f"{len(project.objects())} files in the graph",
        )
        GhidraAdapter().import_directory(
            project, GHIDRA_EXPORT, object_id=agent.artifact_id
        )
        check(
            "functions recovered, so reachability has something to attribute to",
            project.count_artifacts(kind="function", object_id=agent.artifact_id) > 0,
            f"{project.count_artifacts(kind='function', object_id=agent.artifact_id)} functions",
        )

        # -- Phase 1: narrow natural-language interface ---------------------
        heading("2. narrow question interface")
        check(
            "question set is narrow, as specified (4-5 types)",
            4 <= len(QUESTION_TYPES) <= 5,
            f"{len(QUESTION_TYPES)} types: {', '.join(sorted(QUESTION_TYPES))}",
        )

        answered = 0
        uncited: list[str] = []
        for question_type in QUESTION_TYPES.values():
            answer = ask(project, question_type.examples[0])
            validate_answer(answer)
            if not answer.understood:
                uncited.append(f"{question_type.id}: declined its own example")
                continue
            answered += 1
            for line in answer.lines:
                if not line.is_caveat and not line.claim_ids:
                    uncited.append(f"{question_type.id}: {line.text[:40]}")
        check(
            "every question type answers its own example",
            answered == len(QUESTION_TYPES),
            f"{answered}/{len(QUESTION_TYPES)}",
        )
        check(
            "every explanatory line cites the claims it rests on",
            not uncited,
            "the citation invariant holds" if not uncited else f"uncited: {uncited[:2]}",
        )

        secrets = ask(project, "are there any hardcoded secrets?")
        grounded = all(
            f.evidence and f.evidence[0].get("location") for f in secrets.findings
        )
        check(
            "answers resolve to concrete locations in real files",
            bool(secrets.findings) and grounded,
            f"{len(secrets.findings)} findings, first at "
            f"{secrets.findings[0].evidence[0]['location']} in "
            f"{secrets.findings[0].subject_path}",
        )
        check(
            "answers carry caveats rather than overstating",
            bool(secrets.caveats),
            secrets.caveats[0][:64] + "...",
        )

        declined = ask(project, "what CVEs affect this firmware")
        check(
            "an unsupported question is declined, not guessed at",
            not declined.understood and bool(declined.supported),
            f"offered {len(declined.supported)} supported types instead",
        )

        # -- Phase 1: light emulation-based reachability --------------------
        heading("3. reachability")
        availability = QemuAdapter().probe()
        print(
            "  qemu engine: "
            + (
                f"available - {availability.version}"
                if availability.available
                else "not installed; importing a recorded trace instead"
            )
        )

        refused = False
        try:
            QemuAdapter().analyze(project, ELF, allow_execution=False)
        except AdapterError as exc:
            refused = "sandbox" in str(exc)
        check(
            "execution is refused unless explicitly allowed",
            refused,
            "qemu-user is an emulator, not a sandbox",
        )

        traced = QemuAdapter().import_trace(
            project,
            QEMU_TRACE,
            object_id=agent.artifact_id,
            run_label="./firmware_agent AAAA",
        )
        reached = {
            c["statement"]["name"]
            for c in project.find_claims(predicate="function_reached", limit=50)
        }
        check(
            "executed functions become evidence-backed claims",
            bool(reached),
            f"reached {traced.details['functions_reached']} of "
            f"{traced.details['functions_known']} known: {', '.join(sorted(reached))}",
        )

        defined = {
            c["statement"]["name"]
            for c in project.find_claims(predicate="defines_function", limit=50)
        }
        unreached = sorted(defined - reached)
        check(
            "a function that never ran produces no reachability claim",
            bool(unreached),
            f"known but not reached: {', '.join(unreached)}",
        )

        for claim in project.find_claims(predicate="function_reached", limit=50):
            roles = {
                (ref["role"], project.get_artifact(ref["artifact_id"]).kind)
                for ref in claim["evidence"]
            }
            if ("support", "trace_hit") not in roles:
                check("reachability claims cite their runtime observation", False)
                break
        else:
            check(
                "reachability claims cite their runtime observation",
                True,
                "each cites a function locus and a trace_hit in support",
            )

        surface = ask(project, "what is the attack surface?")
        mentions_dynamic = any(
            "executing under emulation" in line.text for line in surface.lines
        )
        check(
            "the attack-surface answer now reports observed execution",
            mentions_dynamic,
            "static surface and dynamic evidence in one cited answer",
        )
        check(
            "the 'reachability unproven' caveat is dropped once a trace exists",
            not any("reachability is unproven" in c for c in surface.caveats),
        )

        # -- Phase 1: measured precision ------------------------------------
        heading("4. measured precision")
        report = run_question_suite(load_suite(NL_SUITE))
        totals = report.totals
        check(
            "the corpus exercises real out-of-scope pressure",
            totals["out_of_scope"] >= 15,
            f"{totals['in_scope']} in scope, {totals['out_of_scope']} out of scope",
        )
        check(
            "question classification suite passes",
            report.passed,
            f"accuracy {totals['accuracy']:.2f}, macro precision "
            f"{totals['macro_precision']:.2f}, macro recall {totals['macro_recall']:.2f}",
        )
        check(
            "no unsupported question was answered anyway",
            totals["false_accepts"] == 0,
            f"{totals['false_accepts']} false accept(s)",
        )

        # -- both front ends -------------------------------------------------
        heading("5. front ends agree")
        server = MCPServer(project)
        response = server.handle_message(
            {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "tools/call",
                "params": {
                    "name": "aether_ask",
                    "arguments": {"question": "are there any hardcoded secrets?"},
                },
            }
        )["result"]
        payload = response["structuredContent"]
        check(
            "the MCP tool returns the same structured answer as the CLI",
            payload["understood"]
            and payload["question_type"] == secrets.question_type
            and set(payload["claim_ids"]) == set(secrets.claim_ids),
            f"{len(payload['claim_ids'])} claim ids, identical on both surfaces",
        )
        check(
            "the evidence graph is still intact after all of it",
            project.check() == [],
        )

        stats = project.stats()
        heading("summary")
        print(
            f"  {stats['totals']['artifacts']} artifacts, "
            f"{stats['totals']['claims']} claims, "
            f"{stats['totals']['attestations']} attestations, "
            f"{stats['totals']['runs']} runs"
        )
        print(f"  claim predicates: {stats['claims_by_predicate']}")

        passed = sum(1 for _n, ok, _d in RESULTS if ok)
        failures = [name for name, ok, _d in RESULTS if not ok]
        print()
        print("=" * 62)
        print(f"  {passed}/{len(RESULTS)} Phase 1 checks passed")
        for name in failures:
            print(f"    - {name}")
        print("=" * 62)
        return 0 if not failures else 1
    finally:
        project.close()
        shutil.rmtree(workspace, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
