"""End-to-end demonstration of the Phase 0 success gate.

Runs the whole pipeline against real files and checks each gate item from the
build specification, printing PASS or FAIL for every one. Exits non-zero if any
item fails, so it doubles as a smoke test.

    python examples/demo_phase0.py

Nothing here is mocked. The ELF and the firmware image are generated by the
scripts in examples/src/ and analysed for real; the PE is compiled locally when
a C compiler is present. The Ghidra stage imports a recorded export, because
Ghidra is a multi-gigabyte install this demo should not require - the import
path being exercised is exactly the one a live Ghidra run feeds into.
"""

from __future__ import annotations

import os
import runpy
import shutil
import sys
import tempfile

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, REPO_ROOT)

from aether.adapters.binwalk import BinwalkAdapter  # noqa: E402
from aether.adapters.ghidra import GhidraAdapter  # noqa: E402
from aether.adapters.triage import TriageAdapter  # noqa: E402
from aether.eval import load_suite, run_suite  # noqa: E402
from aether.export import export_project  # noqa: E402
from aether.mcp.server import MCPServer  # noqa: E402
from aether.project import Project  # noqa: E402

EXAMPLES = os.path.join(REPO_ROOT, "examples")
ELF = os.path.join(EXAMPLES, "firmware_agent.elf")
PE = os.path.join(EXAMPLES, "vulnerable_demo.exe")
FIRMWARE = os.path.join(EXAMPLES, "demo_firmware.bin")
GHIDRA_EXPORT = os.path.join(REPO_ROOT, "tests", "fixtures", "ghidra", "firmware_agent")

RESULTS: list[tuple[str, bool, str]] = []


def have_pe_sample() -> bool:
    """True only when a real PE is sitting at the PE sample path.

    The filename is not evidence. A native gcc on Linux compiles the demo
    source into an ELF and the test fixtures leave it at this path, so
    checking existence alone made the demo assert PE-ness about an ELF.
    """
    try:
        with open(PE, "rb") as handle:
            return handle.read(2) == b"MZ"
    except OSError:
        return False


def check(name: str, condition: bool, detail: str = "") -> bool:
    RESULTS.append((name, bool(condition), detail))
    mark = "PASS" if condition else "FAIL"
    print(f"  [{mark}] {name}" + (f"  -  {detail}" if detail else ""))
    return bool(condition)


def heading(text: str) -> None:
    print(f"\n{text}\n{'-' * len(text)}")


def build_samples() -> None:
    heading("0. sample generation")
    if not os.path.isfile(ELF):
        _run_script(os.path.join(EXAMPLES, "src", "build_elf_sample.py"), ELF)
    if not os.path.isfile(FIRMWARE):
        _run_script(os.path.join(EXAMPLES, "src", "build_firmware_sample.py"), FIRMWARE)
    if not os.path.isfile(os.path.join(GHIDRA_EXPORT, "meta.json")):
        _run_script(os.path.join(REPO_ROOT, "tests", "fixtures", "make_ghidra_fixture.py"))
    check("ELF sample present", os.path.isfile(ELF), os.path.basename(ELF))
    check("firmware sample present", os.path.isfile(FIRMWARE), os.path.basename(FIRMWARE))
    if have_pe_sample():
        print(f"  [ok  ] PE sample present  -  {os.path.basename(PE)}")
    else:
        print(
            "  [skip] no PE sample on this host; PE checks will be skipped "
            "(a native gcc on Linux emits ELF - install mingw-w64 for PE coverage)"
        )


def _run_script(path: str, *args: str) -> None:
    saved = sys.argv
    sys.argv = [path, *args]
    try:
        runpy.run_path(path, run_name="__main__")
    except SystemExit as exc:
        if exc.code not in (0, None):
            raise
    finally:
        sys.argv = saved


def main() -> int:
    print("Aether - Phase 0 gate demonstration")
    print("=" * 60)
    build_samples()

    workspace = tempfile.mkdtemp(prefix="aether-demo-")
    project = Project.create(os.path.join(workspace, "project"), "phase0-demo")

    try:
        # -- gate: analyze common ELF and PE binaries ----------------------
        heading("1. binary analysis (ELF and PE)")
        elf_result = TriageAdapter().analyze(project, ELF, logical_path="bin/firmware_agent")
        elf_object = elf_result.objects[0]
        elf_file = project.get_artifact(elf_object)
        check(
            "ELF identified with architecture and word size",
            elf_file.data.get("format") == "elf" and elf_file.data.get("arch") == "x86_64",
            f"{elf_file.data.get('media_type')}",
        )
        check(
            "ELF sections, imports, and exports recovered",
            project.count_artifacts(kind="section", object_id=elf_object) >= 5
            and project.count_artifacts(kind="import", object_id=elf_object) >= 5
            and project.count_artifacts(kind="export", object_id=elf_object) >= 3,
            f"{project.count_artifacts(kind='section', object_id=elf_object)} sections, "
            f"{project.count_artifacts(kind='import', object_id=elf_object)} imports",
        )

        if have_pe_sample():
            pe_result = TriageAdapter().analyze(project, PE, logical_path="bin/diagnostics.exe")
            pe_file = project.get_artifact(pe_result.objects[0])
            check(
                "PE identified with architecture and mitigations",
                pe_file.data.get("format") == "pe",
                f"{pe_file.data.get('media_type')}",
            )
        else:
            print("  [skip] PE analysis (no PE-emitting toolchain on this host)")

        # -- gate: Ghidra headless results imported ------------------------
        heading("2. Ghidra headless bridge")
        availability = GhidraAdapter().probe()
        print(
            f"  ghidra engine: {'available - ' + availability.version if availability.available else 'not installed on this machine'}"
        )
        strings_before = project.count_artifacts(kind="string", object_id=elf_object)
        imports_before = project.count_artifacts(kind="import", object_id=elf_object)

        ghidra_result = GhidraAdapter().import_directory(
            project, GHIDRA_EXPORT, object_id=elf_object
        )
        imported = ghidra_result.details["imported"]
        check(
            "functions, xrefs, and decompilation imported",
            imported["functions"] > 0 and imported["xrefs"] > 0 and imported["decompilation"] > 0,
            f"{imported['functions']} functions, {imported['xrefs']} xrefs, "
            f"{imported['decompilation']} decompiled",
        )
        check(
            "Ghidra converged onto existing artifacts instead of duplicating",
            project.count_artifacts(kind="string", object_id=elf_object) == strings_before
            and project.count_artifacts(kind="import", object_id=elf_object) == imports_before,
            f"strings stayed at {strings_before}, imports at {imports_before}",
        )
        corroborated = [
            c for c in project.find_claims(limit=500) if c["confidence"]["producers"] > 1
        ]
        check(
            "independent producers corroborate shared claims",
            len(corroborated) > 0,
            f"{len(corroborated)} claims attested by two engines",
        )

        # -- gate: unpack firmware and inventory binaries ------------------
        heading("3. firmware unpacking and inventory")
        firmware = BinwalkAdapter()
        firmware_result = firmware.analyze(project, FIRMWARE, logical_path="demo_firmware.bin")
        inventory = {item["path"]: item for item in firmware_result.details["inventory"]}
        print(f"  extraction engine: {firmware_result.details['engine']}")
        check(
            "nested container chain unpacked (uImage -> gzip -> cpio)",
            "bin/firmware_agent" in inventory and "etc/telemetry.conf" in inventory,
            f"{len(inventory)} files recovered",
        )
        check(
            "extracted binaries inventoried with format and architecture",
            inventory.get("bin/firmware_agent", {}).get("arch") == "x86_64",
            ", ".join(sorted(inventory)[:4]) + " ...",
        )
        secret_subjects = {
            project.get_artifact(c["subject_id"]).data.get("path")
            for c in project.find_claims(predicate="contains_hardcoded_secret", limit=100)
        }
        check(
            "findings attributed to the member file, not the container blob",
            "etc/telemetry.conf" in secret_subjects
            and not any(str(p).endswith(".gunzipped") for p in secret_subjects),
            f"{len(secret_subjects)} distinct files carry secret findings",
        )

        # -- gate: evidence graph links findings to concrete locations -----
        heading("4. evidence graph")
        sample_claim = next(
            c
            for c in project.find_claims(predicate="contains_hardcoded_secret", limit=50)
            if c["evidence"]
        )
        evidence_artifact = project.get_artifact(sample_claim["evidence"][0]["artifact_id"])
        container = project.get_artifact(evidence_artifact.object_id)
        check(
            "claim resolves to a string artifact at a concrete location",
            evidence_artifact.kind == "string" and evidence_artifact.addr_start is not None,
            f"{sample_claim['statement']['secret_kind']} at "
            f"offset/addr {evidence_artifact.addr_start} in {container.data.get('path')}",
        )

        every_claim_backed = True
        for claim in project.find_claims(limit=1000):
            if not claim["evidence"] or not claim["attestations"]:
                every_claim_backed = False
                break
        check(
            "every claim carries evidence and provenance",
            every_claim_backed,
            f"{project.stats()['totals']['claims']} claims checked",
        )
        check(
            "integrity check reports no violations",
            project.check() == [],
        )

        refined = [
            c
            for c in project.find_claims(predicate="uses_risky_api", limit=100)
            if project.claim_links(c["id"])["outgoing"]
        ]
        check(
            "call-site evidence linked as a refinement of the coarse claim",
            len(refined) > 0,
            f"{len(refined)} refined claims",
        )

        # -- gate: MCP tools return structured data ------------------------
        heading("5. MCP server")
        server = MCPServer(project)
        init = server.handle_message(
            {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {}}
        )["result"]
        listed = server.handle_message(
            {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}
        )["result"]["tools"]
        check(
            "protocol handshake and tool discovery",
            init["serverInfo"]["name"] == "aether" and len(listed) >= 10,
            f"protocol {init['protocolVersion']}, {len(listed)} tools",
        )

        def call(name: str, arguments: dict) -> dict:
            return server.handle_message(
                {
                    "jsonrpc": "2.0",
                    "id": 3,
                    "method": "tools/call",
                    "params": {"name": name, "arguments": arguments},
                }
            )["result"]

        search = call("aether_search_strings", {"query": "AKIA"})["structuredContent"]
        check(
            "structured query returns located evidence",
            bool(search["matches"]) and search["matches"][0]["addr"].startswith("0x"),
            f"{len(search['matches'])} match(es), first at {search['matches'][0]['addr']}",
        )

        string_artifact = project.find_artifacts(kind="string", object_id=elf_object, limit=1)[0]
        accepted = call(
            "aether_submit_claim",
            {
                "predicate": "contains_string",
                "statement": {"text": string_artifact.data["text"], "encoding": "ascii"},
                "evidence": [{"artifact_id": string_artifact.artifact_id, "role": "locus"}],
                "confidence": 0.8,
                "producer": "agent:demo",
            },
        )
        check(
            "agent can record a structured, evidence-backed claim",
            not accepted.get("isError"),
            f"stored as {accepted['structuredContent']['status']}",
        )

        refused = call(
            "aether_submit_claim",
            {
                "predicate": "contains_hardcoded_secret",
                "statement": {
                    "secret_kind": "api_token",
                    "detector": "agent:demo",
                    "note": "I think this is exploitable",
                },
                "evidence": [{"artifact_id": string_artifact.artifact_id}],
                "producer": "agent:demo",
            },
        )
        check(
            "free-text claim from an agent is refused",
            bool(refused.get("isError")) and "undeclared" in refused["content"][0]["text"],
            "schema rejected the prose field",
        )

        unevidenced = call(
            "aether_submit_claim",
            {
                "predicate": "contains_hardcoded_secret",
                "statement": {"secret_kind": "api_token", "detector": "agent:demo"},
                "evidence": [],
                "producer": "agent:demo",
            },
        )
        check(
            "claim without evidence from an agent is refused",
            bool(unevidenced.get("isError")),
            "evidence requirement enforced at the interface",
        )

        # -- gate: deterministic, Git-friendly export ----------------------
        heading("6. deterministic export")
        first_export = os.path.join(workspace, "export-1")
        manifest = export_project(project, first_export)
        check(
            "export written with graph and ledger separated",
            os.path.isfile(os.path.join(first_export, "graph", "claims.jsonl"))
            and os.path.isfile(os.path.join(first_export, "ledger", "runs.jsonl")),
            f"graph digest {manifest['graph_digest']}",
        )

        replica_dir = os.path.join(workspace, "replica")
        replica = Project.create(replica_dir, "phase0-demo")
        TriageAdapter().analyze(replica, ELF, logical_path="bin/firmware_agent")
        replica_manifest = export_project(replica, os.path.join(workspace, "export-2"))
        replica.close()

        control = Project.create(os.path.join(workspace, "control"), "phase0-demo")
        TriageAdapter().analyze(control, ELF, logical_path="bin/firmware_agent")
        control_manifest = export_project(control, os.path.join(workspace, "export-3"))
        control.close()
        check(
            "two independent analyses produce byte-identical graphs",
            replica_manifest["graph_digest"] == control_manifest["graph_digest"],
            f"digest {replica_manifest['graph_digest']}",
        )
        check(
            "provenance ledger differs, as it must",
            replica_manifest["files"]["ledger/runs.jsonl"]["digest"]
            != control_manifest["files"]["ledger/runs.jsonl"]["digest"],
            "runs are events, not content",
        )

        # -- gate: claims validated against ground truth -------------------
        heading("7. evaluation against ground truth")
        for suite_name in ("elf_sample.json", "firmware_image.json"):
            suite = load_suite(os.path.join(REPO_ROOT, "eval", "suites", suite_name))
            report = run_suite(suite, base_dir=REPO_ROOT)
            unmet = [r.expectation_id for r in report.results if r.required and not r.satisfied]
            check(
                f"suite '{report.suite}' passes",
                report.passed,
                f"recall {report.totals['recall']:.2f} over "
                f"{report.totals['required']} expectations, "
                f"{report.totals['forbidden_hits']} false positive(s)"
                + (f"; unmet: {unmet}" if unmet else ""),
            )

        # -- summary --------------------------------------------------------
        stats = project.stats()
        heading("summary")
        print(f"  project holds {stats['totals']['artifacts']} artifacts, "
              f"{stats['totals']['claims']} claims, "
              f"{stats['totals']['attestations']} attestations "
              f"across {stats['totals']['runs']} runs")
        print(f"  artifact kinds: {stats['artifacts_by_kind']}")
        print(f"  claim predicates: {stats['claims_by_predicate']}")

        passed = sum(1 for _n, ok, _d in RESULTS if ok)
        print()
        print("=" * 60)
        print(f"  {passed}/{len(RESULTS)} gate checks passed")
        failures = [name for name, ok, _d in RESULTS if not ok]
        if failures:
            print("  failed:")
            for name in failures:
                print(f"    - {name}")
        print("=" * 60)
        return 0 if not failures else 1
    finally:
        project.close()
        shutil.rmtree(workspace, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
